AWSTemplateFormatVersion: 2010-09-09
Description: 'Workshop AIM329'
Resources:
  OSExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: "OpenSearchExecutionRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - opensearch.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: osrolepolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                - sagemaker:*
                - s3:*
                - lambda:*
                - bedrock:*
                - ecr:*
                - aoss:*
                - cloudwatch:*
                Resource: '*'
  SMExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: "SageMakerExecutionRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: smrolepolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                - sagemaker:*
                - s3:*
                - lambda:*
                - bedrock:*
                - ecr:*
                - aoss:*
                - cloudwatch:*
                - cloudformation:ListStacks
                - cloudformation:DescribeStacks
                - cloudformation:DescribeStackResources
                - cloudformation:DescribeStackResource
                Resource: '*'              
  DataAccessPolicy:
    Type: 'AWS::OpenSearchServerless::AccessPolicy'
    Properties:
      Name: aim329-access-policy
      Type: data
      Description: Access policy for aim329 collection
      Policy: !Sub >-
        [{"Description":"Access for cfn user","Rules":[{"ResourceType":"index","Resource":["index/*/*"],"Permission":["aoss:*"]},
        {"ResourceType":"collection","Resource":["collection/aim329"],"Permission":["aoss:*"]}],
        "Principal":["arn:aws:iam::${AWS::AccountId}:role/OpenSearchExecutionRole", "arn:aws:iam::${AWS::AccountId}:role/SageMakerExecutionRole"]}]
  NetworkPolicy:
    Type: 'AWS::OpenSearchServerless::SecurityPolicy'
    Properties:
      Name: aim329-network-policy
      Type: network
      Description: Network policy for aim329 collection
      Policy: >-
        [{"Rules":[{"ResourceType":"collection","Resource":["collection/aim329"]}, {"ResourceType":"dashboard","Resource":["collection/aim329"]}],"AllowFromPublic":true}]
  EncryptionPolicy:
    Type: 'AWS::OpenSearchServerless::SecurityPolicy'
    Properties:
      Name: aim329-security-policy
      Type: encryption
      Description: Encryption policy for aim329 collection
      Policy: >-
        {"Rules":[{"ResourceType":"collection","Resource":["collection/aim329"]}],"AWSOwnedKey":true}
  Collection:
    Type: 'AWS::OpenSearchServerless::Collection'
    Properties:
      Name: aim329
      Type: VECTORSEARCH
      Description: Collection to hold the embeddings for the content to query via chatbot
    DependsOn:
      - EncryptionPolicy
      - NetworkPolicy
      - DataAccessPolicy
  CodeRepository:
    Type: AWS::SageMaker::CodeRepository
    Properties:
      GitConfig:
          RepositoryUrl: https://github.com/aws-samples/reinvent2023-aim-329
  NotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      NotebookInstanceName: aim329
      PlatformIdentifier: notebook-al2-v2
      InstanceType: ml.m5.xlarge
      RoleArn: !GetAtt SMExecutionRole.Arn
      DefaultCodeRepository: !GetAtt CodeRepository.CodeRepositoryName    
Outputs:
  CollectionARN:
    Value: !GetAtt Collection.Arn
  SageMakerNotebookURL:
    Description: SageMaker Notebook Instance
    Value: !Join
      - ''
      - - !Sub 'https://console.aws.amazon.com/sagemaker/home?region=${AWS::Region}#/notebook-instances/openNotebook/'
        - !GetAtt NotebookInstance.NotebookInstanceName
        - '?view=classic'  